// Cross-platform pairing fixture, production direction (#14): the Pi seals
// the credential envelope with the real rapid-pi code (seal_pairing_key(),
// exactly what PairingCoordinator::consume_impl() calls after panel/setup-
// page approval), using a fixed, deterministic test companion key. The
// Windows companion self-test (pairing_pi_seals_interop_self_test() in
// companion/native/rapid-telemetry-daemon.cpp) decrypts the written
// envelope with the real --pairing-url client code
// (decrypt_pairing_envelope()) and checks it recovers the same plaintext.
//
// This is the reverse of pairing_interop_tests.cpp's direction, which feeds
// Windows-sealed material to the Pi's OpenSSL reference decrypt -- useful,
// but not the direction a real pairing exchange uses. This one is: it is
// the exact path the #14 CNG/OpenSSL byte-order bug broke (every real
// pairing failed post-approval despite both sides' self-tests passing).
//
// device_id/transaction_id/nonce/companion_private_key below are fixed,
// obviously-synthetic constants (repeated hex digit patterns), never a real
// device's identity or key. The Pi's ephemeral key and the resulting
// envelope are freshly generated by the real sealing code each run, exactly
// like a real pairing exchange; a committed snapshot lives in
// cpp/tests/pairing-fixtures-pi-seals/ so the Windows self-test has
// something to consume even without rebuilding this generator first. See
// developer/handoffs/2026-09-17-f4-pairing-kat.md.
#include "rapid/pairing.hpp"
#include <fstream>
#include <iostream>
#include <openssl/evp.h>
#include <sstream>

using namespace rapid::native;

namespace {
void require(bool ok, const char *message) {
  if (!ok) throw std::runtime_error(message);
}

// Mirrors pairing_tests.cpp's derive_public_key(): duplicated here rather
// than exported from pairing.hpp, since only test code needs to turn a raw
// test private key into its X25519 public counterpart.
std::string derive_public_key(const std::string &private_hex) {
  std::string bytes(32, '\0');
  for (std::size_t i = 0; i < 32; ++i)
    bytes[i] = static_cast<char>(std::stoi(private_hex.substr(i * 2, 2), nullptr, 16));
  EVP_PKEY *key = EVP_PKEY_new_raw_private_key(EVP_PKEY_X25519, nullptr,
      reinterpret_cast<const unsigned char *>(bytes.data()), bytes.size());
  std::string result(32, '\0');
  std::size_t size = result.size();
  require(key && EVP_PKEY_get_raw_public_key(key, reinterpret_cast<unsigned char *>(result.data()), &size) > 0,
          "derive test X25519 public key");
  EVP_PKEY_free(key);
  std::ostringstream out;
  for (unsigned char byte : result)
    out << std::hex << std::setw(2) << std::setfill('0') << int(byte);
  return out.str();
}

std::string base64_decode_local(const std::string &value) {
  require(!value.empty() && value.size() % 4 == 0, "invalid base64 while tampering fixture");
  std::string result(3 * value.size() / 4, '\0');
  const auto size = EVP_DecodeBlock(reinterpret_cast<unsigned char *>(result.data()),
                                    reinterpret_cast<const unsigned char *>(value.data()),
                                    static_cast<int>(value.size()));
  require(size >= 0, "invalid base64 while tampering fixture");
  const std::size_t padding = value.ends_with("==") ? 2 : value.ends_with('=') ? 1 : 0;
  result.resize(static_cast<std::size_t>(size) - padding);
  return result;
}

std::string base64_encode_local(const std::string &value) {
  std::string result(4 * ((value.size() + 2) / 3), '\0');
  const auto size = EVP_EncodeBlock(reinterpret_cast<unsigned char *>(result.data()),
                                    reinterpret_cast<const unsigned char *>(value.data()),
                                    static_cast<int>(value.size()));
  result.resize(static_cast<std::size_t>(size));
  return result;
}
} // namespace

int main(int argc, char **argv) {
  try {
    require(argc == 2, "output fixture directory required");
    const fs::path root = argv[1];
    fs::create_directories(root);

    const std::string device_id(32, 'a');
    const std::string transaction_id(32, 'b');
    const std::string nonce(32, 'c');
    const std::string companion_private_key(64, 'd');
    const auto companion_public_key = derive_public_key(companion_private_key);

    // The real Pi sealing code: production's
    // PairingCoordinator::consume_impl() calls exactly this after the
    // physical/panel approval succeeds.
    const auto sealed = seal_pairing_key(device_id, transaction_id, nonce, companion_public_key);

    // Sanity round trip through the Linux reference implementation first,
    // so a local bug in this generator is caught separately from the
    // Windows interop this fixture exists to check.
    require(open_pairing_key(device_id, transaction_id, nonce, companion_private_key,
                             sealed.envelope) == sealed.telemetry_key,
            "Pi-sealed envelope must round-trip through the Linux reference decrypt first");

    auto write_text = [&](const char *name, const std::string &text) {
      std::ofstream out(root / name);
      out << text << '\n';
      require(bool(out), "cannot write pi-seals fixture file");
    };
    write_text("device-id.hex", device_id);
    write_text("transaction-id.hex", transaction_id);
    write_text("nonce.hex", nonce);
    write_text("companion-private-key.hex", companion_private_key);
    write_text("companion-public-key.hex", companion_public_key);
    write_text("pi-ephemeral-public-key.hex", sealed.envelope.ephemeral_public_key);
    write_text("envelope-nonce.b64", sealed.envelope.nonce);
    write_text("envelope-ciphertext.b64", sealed.envelope.ciphertext);
    write_text("envelope-tag.b64", sealed.envelope.tag);
    write_text("expected-plaintext.hex", sealed.telemetry_key);

    // Tampered variant: flip one ciphertext byte. The real
    // decrypt_pairing_envelope() must reject this (AES-GCM tag mismatch);
    // proven by the Windows self-test, but sanity-checked here too against
    // the Linux reference decrypt before it is committed to disk.
    const auto raw_ciphertext = base64_decode_local(sealed.envelope.ciphertext);
    auto tampered_raw = raw_ciphertext;
    tampered_raw[0] = static_cast<char>(tampered_raw[0] ^ 0x01);
    const auto tampered_ciphertext = base64_encode_local(tampered_raw);
    write_text("tampered-envelope-ciphertext.b64", tampered_ciphertext);
    {
      auto tampered_envelope = sealed.envelope;
      tampered_envelope.ciphertext = tampered_ciphertext;
      bool rejected = false;
      try {
        (void)open_pairing_key(device_id, transaction_id, nonce, companion_private_key, tampered_envelope);
      } catch (const std::exception &) {
        rejected = true;
      }
      require(rejected, "tampered ciphertext must be rejected by the Linux reference decrypt too");
    }

    std::cout << "Pi-seals pairing fixture written (production direction, #14): " << root.string() << '\n';
    return 0;
  } catch (const std::exception &error) {
    std::cerr << "pairing pi-seals fixture generator failed: " << error.what() << '\n';
    return 1;
  }
}
